management:
  endpoints:
    web:
      base-path: /manage
    health:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /shop

spring:
  datasource:
    url: jdbc:mysql://phoenix-database:3306/shop
    username: dev
    password: s3cure
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        generate_statistics: true
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace